# Generated by Django 4.0.1 on 2022-11-26 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_authour'),
        ('users', '0002_rename_name_useracounts_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='useracounts',
        ),
    ]
