# Generated by Django 4.0.1 on 2022-11-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_post_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail_des',
            field=models.CharField(default='coding', max_length=100),
        ),
    ]
